export interface Member {
  id: number;
  member_id: number;
  aa_member_no: number | null;
  surname: string;
  onames: string;
  paddress: string;
  email: string;
  tel: string;
  mobile: string;
  passport: string;
  raddress: string;
  street: string;
  pob: string;
  dob: string;
  licence: string;
  classes: string;
  e_date: string;
  pp_photo: string | null;
  p_date: string;
}

export interface CreateMemberData extends Omit<Member, 'id' | 'member_id'> {
  // Excludes both id and member_id as they are auto-generated by the backend
  isMember: boolean
}

export interface PendingIdpData {
  status: string;
  application_date: string;
  application_date_tz: number;
}

export interface IdpDocument {
  visa_pdf_base64: string;
  passport_pdf_base64: string;
  passport_photo_base64: string;
}

export interface CreateMemberResponse {
  data: Member | null;
  error: string | null;
}

export interface IdpVerificationResult {
  idpNumber: number;
  holderName?: string;
  issueDate?: string;
  expiryDate?: string;
  licenseNumber?: string;
  licenseClasses?: string;
  applicationStatus?: string;
  membershipType?: string;
  validityStatus?: string;
  type?: string;
  issuingAuthority?: string;
  contactEmail?: string;
  contactMobile?: string;
  dateOfBirth?: string;
  message?: string;
}

export interface verifyIdpResultProp extends Member {
  idp_available: boolean;
  issuedate: string;
  expirydate: string;
}

export interface IdpVerificationResponse {
  data: verifyIdpResultProp | null;
  error: string | null;
}

export interface AauMember {
  member_id: number;
  aa_member_no: number;
  fname: string;
  onames: string;
  reg_no: string;
  nationality: string;
  postaladdress: string;
  physicaladdress: string;
  tel: string;
  email: string;
  renew_date: string | null;
  period_paid_in_months: number;
  appn_date: string; // ISO 8601 datetime format
  membership_type: string;
  id: number;
}
