export interface Member {
  id: number;
  member_id: number;
  aa_member_no: number | null;
  surname: string;
  onames: string;
  paddress: string;
  email: string;
  tel: string;
  mobile: string;
  passport: string;
  raddress: string;
  street: string;
  pob: string;
  dob: string;
  licence: string;
  classes: string;
  e_date: string;
  pp_photo: string | null;
  p_date: string;
}

export interface CreateMemberData extends Omit<Member, 'id' | 'member_id'> {
  // Excludes both id and member_id as they are auto-generated by the backend
}

export interface PendingIdpData {
  status: string;
  application_date: string;
  application_date_tz: number;
}

export interface CreateMemberResponse {
  data: Member | null;
  error: string | null;
}
